# Generated by Django 3.1.7 on 2022-04-21 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Computer Science and Engineering', 'CSE'), ('Mathematics and Computing', 'MNC'), ('Electrical and Electronics Engineering', 'EEE'), ('Electronics and Communication Engineering', 'ECE'), ('Mechanical Engineering', 'ME'), ('Engineering Physics', 'EP'), ('Data Science and Artificial Intelligence', 'DSAI'), ('Chemical Engineering', 'CL'), ('Chemical Science and Technology', 'CST'), ('Biosciences and Bioengineering', 'BSBE')], max_length=50)),
                ('graduation_year', models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=50)),
                ('programme', models.CharField(choices=[('B. Tech.', 'btech'), ('M. Tech.', 'mtech'), ('Ph. D.', 'phd')], max_length=50)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
