# Generated by Django 3.1.7 on 2022-04-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220422_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='graduation_year',
            field=models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='programme',
            field=models.CharField(choices=[('B. Tech.', 'B. Tech'), ('M. Tech.', 'M. Tech'), ('Ph. D.', 'Ph. D.')], max_length=50),
        ),
    ]
