# Generated by Django 3.1.7 on 2022-04-22 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('experience_type', models.CharField(choices=[('Placement', 'Placement'), ('Intern', 'Intern'), ('Scholarship', 'Scholarship')], max_length=30)),
                ('recruitement_process', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Coding', 'Coding'), ('Group Discussion', 'Group Discussion'), ('Technical Round', 'Technical Round'), ('HR Round', 'HR Round'), ('Managerial Round', 'Managerial Round')], max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience.experience')),
            ],
        ),
        migrations.CreateModel(
            name='Effort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to=None)),
                ('resources', models.CharField(blank=True, max_length=100, null=True)),
                ('efforts', models.CharField(blank=True, max_length=100, null=True)),
                ('tips', models.CharField(blank=True, max_length=500, null=True)),
                ('experience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='experience.experience')),
            ],
        ),
    ]
