# Generated by Django 3.1.7 on 2022-04-23 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='round',
            name='type',
            field=models.CharField(blank=True, choices=[('Coding', 'Coding'), ('Group Discussion', 'Group Discussion'), ('Technical Round', 'Technical Round'), ('HR Round', 'HR Round'), ('Managerial Round', 'Managerial Round')], max_length=100),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='experience.experience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
